Changed Ruby to 2.4.0
CareerAtlas/career_atlas pull request #95
Opened 2017-05-03 21:25 UTC by Rdore88

2017-05-03 22:51 UTC, jenniferoakes commented
@rposborne may I merge this?

2017-05-03 23:22 UTC, rposborne commented
@Rdore88 why are you rolling back to 2.4.1?   You are going to require your entire team to install a new ruby by this change.

2017-05-03 23:45 UTC, Rdore88 commented
@rposborne Sorry Patrick and I were playing around with it for a little bit. I changed it back but I keep getting this message:
/home/travis/build/CareerAtlas/career_atlas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `rescue in connect': FATAL:  database "CareerAtlas_test" does not exist (ActiveRecord::NoDatabaseError)

2017-05-04 00:36 UTC, Rdore88 commented
@jenniferoakes @rposborne I got it fixed but I can't tell if the front end tests are passing.

2017-05-04 02:09 UTC, jenniferoakes commented
@Rdore88 @rposborne wait until tomorrow until we can review in person?

2017-05-04 02:38 UTC, rposborne requested changes

2017-05-04 02:38 UTC, rposborne commented on config/database.yml
> +  database: travis_ci_test
Doesn't this break your tests locally? you changed your db name?   Can't we just ask travis to make a database with the same name?     Inside of our `.travis.yml` we need to run this `psql -c 'create database CareerAtlas_test;' -U postgres` as a before script.   That will ensure that the db exists on travis prior to tests running.

2017-05-04 03:05 UTC, Rdore88 commented on config/database.yml
> +  database: travis_ci_test
@rposborne I did what you said and now the local tests work but travis ci doesn't.

2017-05-04 03:05 UTC, Rdore88 commented on config/database.yml
> +  database: travis_ci_test
@rposborne Your right they did break my local tests but when I changed it travisCI broke.

2017-05-04 13:28 UTC, rposborne approved these changes

2017-05-04 13:28 UTC, merged